[data]
assets_dir = "assets"
artifacts_dir = "artifacts"
filename = "names.txt"
url = "https://rickandmorty.fandom.com/wiki/Category:Characters"

[model]
embedding_dim = 32
hidden_dim = 64
num_layers = 2
vocab_size = 100

[training]
epochs = 800
learning_rate = 0.1
batch_size = 16
factor = 0.1
patience = 50
min_lr = 0.0001