services:

  backend:
    build:
      context: ./services/backend
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs/backend:/app/logs
    ports:
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:443/health && exit 0 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
      
  frontend:
    build:
      context: ./services/frontend
    volumes:
      - ./logs/frontend:/app/logs
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health && exit 0 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped