[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.2",
    "loguru>=0.7.3",
    "uvicorn>=0.38.0",
    "tokenizers>=0.22.1",
    "torch>=2.9.1",
]
